# Generated by Django 5.2.13 on 2026-04-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='avg_rate',
        ),
    ]
