# Generated by Django 5.2.13 on 2026-04-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_comment_project_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
