# Generated by Django 5.2.13 on 2026-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_image'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE projects_project "
                        "ADD COLUMN IF NOT EXISTS avg_rate double precision "
                        "NOT NULL DEFAULT 0"
                    ),
                    reverse_sql="ALTER TABLE projects_project DROP COLUMN IF EXISTS avg_rate",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='avg_rate',
                    field=models.FloatField(blank=True, default=0),
                ),
            ],
        ),
    ]
