# Generated by Django 5.2.13 on 2026-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projects.tag'),
        ),
    ]
