# Generated by Django 5.2.13 on 2026-04-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_avg_rate'),
        ('projects', '0014_alter_tag_name'),
    ]

    operations = [
    ]
