# Generated by Django 5.2.13 on 2026-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_merge_0011_project_avg_rate_0014_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, max_length=10000, null=True, upload_to='project/'),
        ),
    ]
