# Generated by Django 5.2.13 on 2026-04-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='avg_rate',
        ),
    ]
