# Generated by Django 5.2.13 on 2026-04-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_comment_parent"),
        ("projects", "0017_remove_project_avg_rate"),
    ]

    operations = []
