# Generated by Django 5.2.13 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_merge_0017_comment_parent_0017_remove_project_avg_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="projects.tag"),
        ),
    ]
